### ISSUE TITLE
Location Card - Facility Open

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#39]
Not sure what's going @christinerosa . For whatever reason, the location card open status isn't displaying in the development branch...and of course, if I switch back to your branch...it works 🤦 

You're closest to the code. Mind looking into it?

**Comment by christinerosa** [comment]
@arissberg oi vey, I'll pull the development branch and see what's up - maybe something to do with date fns - I'm using functions from that library to handle everything. Will look on Tuesday (possibly Sunday if I'm in decent shape after post wedding celebrations )

**Comment by arissberg** [comment]
@christinerosa you will not!!! 😃 TUESDAY only. Go enjoy your weekend.

**Comment by christinerosa** [comment]
LocationStatus folder index file was missing components - @arissberg fixed in development. Closing bug.
