### ISSUE TITLE
Location Card - Distance should only display if address supplied

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#41]
When no address is provided and we're just showing the raw page Gatsby GraphQL data, the facility distance text should be removed. 

It's confusing right now.

**Comment by christinerosa** [comment]
@arissberg ah okay, I think it's pulling the distance from the default HQ location then - should be an easy fix. Will do on Tuesday.

**Comment by christinerosa** [comment]
Done - will finish fixing other location card bugs and add enhancements, then I'll create a PR
