### ISSUE TITLE
Location Cards - Site isn't open yet but hours of operation says "Open"

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#56]
<img width="363" alt="Screen Shot 2021-07-28 at 12 41 56 PM" src="https://user-images.githubusercontent.com/1923932/127362807-a73225da-cf2e-4889-b283-802dae3fdb7a.png">

I think we should just hide the "Open" || "Closed" etc text - thoughts?

**Comment by christinerosa** [comment]
![image](https://user-images.githubusercontent.com/44384344/127390983-7c3036b4-f4d3-4866-8f63-ddc88011e602.png)

Open status is hidden if coming soon flag is passed into the card.
