### ISSUE TITLE
Locations Search Filters - Should indicate defaults

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#59]
The filters on the location search should show the default search which is all age groups checked and 20+ km distance (if that's the default)

<img width="308" alt="Screen Shot 2021-07-28 at 1 09 46 PM" src="https://user-images.githubusercontent.com/1923932/127366428-21b63fe0-4e8f-47b5-9955-2af43ded9754.png">

**Comment by christinerosa** [comment]
Done
