### ISSUE TITLE
Locations Search - ✕ should be darker and have hover/focus styling

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#60]
The current ✕ doesn't have enough contrast for AODA. Let's make it either a darker gray or purple.

It also needs hover/focus styling

<img width="1063" alt="Screen Shot 2021-07-28 at 1 41 05 PM" src="https://user-images.githubusercontent.com/1923932/127370566-fd8805e2-5a5f-4a1c-a686-3aa0d38d642b.png">

**Comment by christinerosa** [comment]
Made it a darker gray with purple on hover. Added outline for focus - tried to just change the colour to purple on focus as well but it wouldn't take.  @arissberg let me know how I might be able to do that or if you have a different focus style in mind.
