### ISSUE TITLE
Locations Page - Google Map

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#61]
The temporary embedded Google map needs to be replaced with a map rendered via the Google Maps API.

- Disable all controls (Zoom, pan etc)
- Center map on center of hamilton, but don't worry about fitting all locations in view
- Use our locations data to place makers on the map

We could also look at doing this https://geo-devrel-io2021-oobe.web.app/#integrated-camera-control

**Comment by christinerosa** [comment]
Replaced - could use minor tweaks but it checks off all the requirements.
