### ISSUE TITLE
Location Autocomplete - Clear search ✕ should be a part of the input 

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#65]
The ✕ should be moved inside the input container. Then we won't have to worry about styling changes if the input is put on a dark background

<img width="496" alt="Screen Shot 2021-07-28 at 2 27 49 PM" src="https://user-images.githubusercontent.com/1923932/127376647-b514b67c-6263-4739-8b6d-4cae9b37822a.png">

**Comment by arissberg** [comment]
Note that the ✕ only shows if you have something typed in the input

**Comment by christinerosa** [comment]
Done!
