### ISSUE TITLE
Location Search Filter - Age Group options shouldn't be hard coded

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#67]
The age group options in the filter drop down are hardcoded. This should be a prop that's passed in and the options determined by what data the page got from gatsby/api

<img width="682" alt="Screen Shot 2021-07-29 at 11 54 54 AM" src="https://user-images.githubusercontent.com/1923932/127524768-a4a112e5-5282-4c65-bee0-e86ae78cfce4.png">

**Comment by christinerosa** [comment]
Done
