### ISSUE TITLE
Location Card - Open status doesn't seem to work

### ISSUE THREAD

**Issue by arissberg** [arissberg/umbrella-gatsby-site#68]
It's 12:10am and the locations all say "Open"

**Steps to reproduce:**

- Visit https://umbrellagatsbysitedevelopment.gtsb.io/locations/ at 12:10am 🤷 

<img width="448" alt="Screen Shot 2021-07-30 at 12 10 45 AM" src="https://user-images.githubusercontent.com/1923932/127598969-4cdb9a3c-4aa6-4e01-b4e3-0e01ee29332d.png">

**Comment by christinerosa** [comment]
Was missing condition for hours that are less than closed and open hour - fixed.
